# Core Settings
title: Kanpov's Hub
email: karpovanton729@gmail.com
description: >-
  A website hosting my articles, newsletter, projects and much more!
baseurl: ""
url: ""
search: true

# Content Settings
collections:
  articles:
    output: true

paginate_path: /page:num/
paginate: 3

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _articles
  - scope:
      path: ""
      type: "articles"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Styling Settings
minimal_mistakes_skin: dark

author:
  name: "Karpov Anton"
  bio: "Formerly developed Minecraft mods and 2D games, currently learning 3D game development and 3D art."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kanpov/"
    - label: "Newsletter"
      icon: "fas fa-fw fa-link"
      url: "https://kanpov.github.io/feed.xml"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kanpov/"

# System Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - .idea
  - .jekyll-cache
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - _site
  - .git
